name = "GeneralUtils"                                                                                  
uuid = "16fdc788-0fe9-4864-8519-57fb7aaae269"                                                                      
version = "0.1.0"
